[workspace]
members = ["methods", "relay"]

[workspace.dependencies]
# DO NOT MERGE: Update this to a release tag
risc0-build = { git = "https://github.com/risc0/risc0", branch = "capossele/governance-example" }
risc0-zkvm = { git = "https://github.com/risc0/risc0", branch ="capossele/governance-example", default-features = false }
bonsai-sdk = { git = "https://github.com/risc0/risc0", branch = "capossele/governance-example"}
bonsai-ethereum-relay = { git = "https://github.com/risc0/risc0", branch = "capossele/governance-example"}
methods = { path = "./methods", package = "bonsai-starter-methods" }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
